<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EmployeeHub.DataAccess\EmployeeHub.DataAccess.csproj" />
    <ProjectReference Include="..\EmployeeHub.Entities\EmployeeHub.Entities.csproj" />
    <ProjectReference Include="..\EmployeeHub.Common\EmployeeHub.Common.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
